# Generated by Django 6.0.8 on 2026-09-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='pedidos.mesa')),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.cuenta'),
        ),
        migrations.AddConstraint(
            model_name='cuenta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('mesa',), name='unique_cuenta_abierta_por_mesa'),
        ),
    ]
