# Generated by Django 6.0.8 on 2026-09-30 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_cuenta_pedido_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedidos.cuenta'),
        ),
    ]
