# Generated by Django 6.0.8 on 2026-09-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='estado_preparacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En preparación'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20),
        ),
    ]
