# Generated by Django 6.0.8 on 2026-10-01 07:04

import django.db.models.deletion
from django.db import migrations, models


def migrar_preparaciones(apps, schema_editor):
    DetallePedido = apps.get_model("pedidos", "DetallePedido")
    PreparacionPedidoSector = apps.get_model(
        "pedidos",
        "PreparacionPedidoSector",
    )
    database = schema_editor.connection.alias
    estados_por_sector = {}

    detalles = DetallePedido.objects.using(database).values_list(
        "pedido_id",
        "sector_destino_id",
        "estado_preparacion",
    )
    for pedido_id, sector_id, estado in detalles.iterator():
        estados_por_sector.setdefault((pedido_id, sector_id), set()).add(estado)

    ambiguos = [
        (pedido_id, sector_id, estados)
        for (pedido_id, sector_id), estados in estados_por_sector.items()
        if len(estados) != 1
    ]
    if ambiguos:
        raise RuntimeError(
            "No se pueden migrar estados de preparación distintos para "
            f"el mismo Pedido y sector: {ambiguos}"
        )

    PreparacionPedidoSector.objects.using(database).bulk_create(
        [
            PreparacionPedidoSector(
                pedido_id=pedido_id,
                sector_id=sector_id,
                estado=next(iter(estados)),
            )
            for (pedido_id, sector_id), estados in estados_por_sector.items()
        ]
    )


def restaurar_estados_detalle(apps, schema_editor):
    DetallePedido = apps.get_model("pedidos", "DetallePedido")
    PreparacionPedidoSector = apps.get_model(
        "pedidos",
        "PreparacionPedidoSector",
    )
    database = schema_editor.connection.alias

    for preparacion in PreparacionPedidoSector.objects.using(database).iterator():
        DetallePedido.objects.using(database).filter(
            pedido_id=preparacion.pedido_id,
            sector_destino_id=preparacion.sector_id,
        ).update(estado_preparacion=preparacion.estado)


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_detallepedido_estado_preparacion'),
        ('usuarios', '0003_alter_user_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparacionPedidoSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PREPARACION', 'En preparación'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparaciones_sectoriales', to='pedidos.pedido')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preparaciones_pedido', to='usuarios.sector')),
            ],
            options={
                'ordering': ['pedido_id', 'sector__nombre'],
                'constraints': [models.UniqueConstraint(fields=('pedido', 'sector'), name='unique_preparacion_pedido_sector')],
            },
        ),
        migrations.RunPython(
            migrar_preparaciones,
            restaurar_estados_detalle,
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='estado_preparacion',
        ),
    ]
