# Generated by Django 6.0.8 on 2026-10-06 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_remove_detallepedido_estado_preparacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='retiro_habilitado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='retiro_habilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retiros_habilitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvisoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_retiro', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_retiro', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(fields=('pedido',), name='unique_aviso_retiro_por_pedido')],
            },
        ),
    ]
