# Generated by Django 6.0.8 on 2026-09-09 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('SALON', 'Salón'), ('BARRA', 'Barra'), ('PIZZA', 'Pizza'), ('PLATOS', 'Platos')], max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'Administrador'), ('MOZO', 'Mozo'), ('BARRA', 'Barra'), ('COCINA', 'Cocina')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.sector'),
        ),
    ]
