# Generated by Django 6.0.8 on 2026-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sector_user_rol_user_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('MOZO', 'Mozo'), ('BARRA', 'Barra'), ('COCINA', 'Cocina')], max_length=20),
        ),
    ]
